doctrine:
    dbal:
        default_connection: symfony6_database_2
        connections:
            default:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL)%'

            symfony6_database_2:
                # configure these for your database server
                url: '%env(resolve:DATABASE_KEN_URL)%'
                
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'

    orm:
        default_entity_manager: symfony6_database_2
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            symfony6_database_2:
                connection: symfony6_database_2
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    symfony6_database_2:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: symfony6_database_2
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
